//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compras_Inventario_Fereteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compras
    {
        public int id_compras { get; set; }
        public int id_usuario { get; set; }
        public int id_producto { get; set; }
        public int cantidad { get; set; }
        public double total_compra { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
