//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compras_Inventario_Fereteria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class compras
    {
        public int id_compras { get; set; }

        [Display(Name = "Nombre del Empleado")]
        public int id_empleado { get; set; }

        [Required()]
        [Display(Name = "Total de la Compra")]
        public double total_compra { get; set; }

        [Required()]
        [Display(Name = "Cantidad")]
        public int cantidad { get; set; }

        [Required()]
        [Display(Name = "Fecha de Compra")]
        public System.DateTime fecha { get; set; }
    
        public virtual empleado empleado { get; set; }
    }
}
