//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compras_Inventario_Fereteria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class compras
    {
        public int id_compras { get; set; }

        [Required]
        [Display(Name = "Nombre de Usuario")]
        public int id_usuario { get; set; }

        [Required]
        [Display(Name = "Producto")]
        public int id_producto { get; set; }

        [Required]
        [Display(Name = "Cantidad")]
        public int cantidad { get; set; }

        [Required]
        [Display(Name = "Total Compra")]
        public double total_compra { get; set; }

        [Required]
        [Display(Name = "Fecha de la Compra")]
        public System.DateTime fecha { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
